In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
df=pd.read_csv('/content/drive/MyDrive/Global Super Store Dataset/Global_Superstore2.csv',encoding = 'unicode_escape')

In [9]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
5,22732,IN-2013-42360,28-06-2013,01-07-2013,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,...,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.35,Critical
6,30570,IN-2011-81826,07-11-2011,09-11-2011,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,...,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.77,Critical
7,31192,IN-2012-86369,14-04-2012,18-04-2012,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,...,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.4800,878.38,High
8,40155,CA-2014-135909,14-10-2014,21-10-2014,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,1906.4850,867.69,Low
9,40936,CA-2012-116638,28-01-2012,31-01-2012,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical

In [19]:
df.tail(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51280,46582,TU-2014-6730,29-11-2014,30-11-2014,First Class,KF-6285,Karen Ferguson,Home Office,Midyat,Mardin,...,OFF-BOS-10000350,Office Supplies,Art,"Boston Pens, Blue",34.128,6,0.6,-49.5720,0.02,Medium
51281,6039,MX-2014-169530,09-06-2014,11-06-2014,First Class,HG-15025,Hunter Glantz,Consumer,Bragança Paulista,São Paulo,...,OFF-PA-10002418,Office Supplies,Paper,"Green Bar Message Books, Multicolor",84.000,5,0.0,9.2000,0.02,High
51282,9922,MX-2012-100258,28-12-2012,31-12-2012,First Class,KM-16375,Katherine Murray,Home Office,Managua,Managua,...,OFF-PA-10004020,Office Supplies,Paper,"SanDisk Message Books, 8.5 x 11",18.640,1,0.0,8.0000,0.01,Medium
51283,24105,IN-2014-72327,30-05-2014,30-05-2014,Same Day,KH-16330,Katharine Harms,Corporate,Lucknow,Uttar Pradesh,...,OFF-PA-10000215,Office Supplies,Paper,"Eaton Parchment Paper, Premium",26.940,2,0.0,1.8600,0.01,High
51284,24175,IN-2014-57662,05-08-2014,10-08-2014,Standard Class,DB-13270,Deborah Brumfield,Home Office,Townsville,Queensland,...,OFF-BI-10002424,Office Supplies,Binders,"Avery Binder, Economy",58.050,5,0.1,19.9500,0.01,Medium
51285,29002,IN-2014-62366,19-06-2014,19-06-2014,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.01,Medium
51286,35398,US-2014-102288,20-06-2014,24-06-2014,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.01,Medium
51287,40470,US-2013-155768,02-12-2013,02-12-2013,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.01,High
51288,9596,MX-2012-140767,18-02-2012,22-02-2012,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.00,Medium
51289,6147,MX-2012-134460,22-05-2012,26-05-2012,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.00,High

In [10]:
print(df)

       Row ID         Order ID  Order Date   Ship Date       Ship Mode  \
0       32298   CA-2012-124891  31-07-2012  31-07-2012        Same Day
1       26341    IN-2013-77878  05-02-2013  07-02-2013    Second Class
2       25330    IN-2013-71249  17-10-2013  18-10-2013     First Class
3       13524  ES-2013-1579342  28-01-2013  30-01-2013     First Class
4       47221     SG-2013-4320  05-11-2013  06-11-2013        Same Day
...       ...              ...         ...         ...             ...
51285   29002    IN-2014-62366  19-06-2014  19-06-2014        Same Day
51286   35398   US-2014-102288  20-06-2014  24-06-2014  Standard Class
51287   40470   US-2013-155768  02-12-2013  02-12-2013        Same Day
51288    9596   MX-2012-140767  18-02-2012  22-02-2012  Standard Class
51289    6147   MX-2012-134460  22-05-2012  26-05-2012    Second Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
1        JR-16210     Justin Ritter    Corporate     Wollongong
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
...           ...               ...          ...            ...
51285    KE-16420   Katrina Edelman    Corporate           Kure
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston
51287    LB-16795    Laurel Beltran  Home Office         Oxnard
51288    RB-19795        Ross Baird  Home Office       Valinhos
51289    MC-18100     Mick Crebagga     Consumer       Tipitapa

                 State  ...        Product ID         Category Sub-Category  \
0             New York  ...   TEC-AC-10003033       Technology  Accessories
1      New South Wales  ...   FUR-CH-10003950        Furniture       Chairs
2           Queensland  ...   TEC-PH-10004664       Technology       Phones
3               Berlin  ...   TEC-PH-10004583       Technology       Phones
4                Dakar  ...  TEC-SHA-10000501       Technology      Copiers
...                ...  ...               ...              ...          ...
51285        Hiroshima  ...   OFF-FA-10000746  Office Supplies    Fasteners
51286            Texas  ...   OFF-AP-10002906  Office Supplies   Appliances
51287       California  ...   OFF-EN-10001219  Office Supplies    Envelopes
51288        São Paulo  ...   OFF-BI-10000806  Office Supplies      Binders
51289          Managua  ...   OFF-PA-10004155  Office Supplies        Paper

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
1              Novimex Executive Leather Armchair, Black  3709.395        9
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
...                                                  ...       ...      ...
51285                      Advantus Thumb Tacks, 12 Pack    65.100        5
51286  Hoover Replacement Belt for Commercial Guardsm...     0.444        1
51287       #10- 4 1/8" x 9 1/2" Security-Tint Envelopes    22.920        3
51288                            Acco Index Tab, Economy    13.440        2
51289            Eaton Computer Printout Paper, 8.5 x 11    61.380        3

      Discount    Profit  Shipping Cost  Order Priority
0          0.0  762.1845         933.57        Critical
1          0.1 -288.7650         923.63        Critical
2          0.1  919.9710         915.49          Medium
3          0.1  -96.5400         910.16          Medium
4          0.0  311.5200         903.04        Critical
...        ...       ...            ...             ...
51285      0.0    4.5000           0.01          Medium
51286      0.8   -1.1100           0.01          Medium
51287      0.0   11.2308           0.01            High
51288      0.0    2.4000           0.00          Medium
51289      0.0    1.8000           0.00            High

[51290 rows x 24 columns]

In [20]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51285    False
51286    False
51287    False
51288    False
51289    False
Length: 51290, dtype: bool

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

In [13]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
City               object
State              object
Country            object
Postal Code       float64
Market             object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
Shipping Cost     float64
Order Priority     object
dtype: object

In [63]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,51290.00000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,55190.379428,246.490581,3.476545,0.142908,28.610982,26.375915
std,14806.29199,32063.693350,487.565361,2.278766,0.212280,174.340972,57.296804
min,1.00000,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000
25%,12823.25000,23223.000000,30.758625,2.000000,0.000000,0.000000,2.610000
50%,25645.50000,56430.500000,85.053000,3.000000,0.000000,9.240000,7.790000
75%,38467.75000,90008.000000,251.053200,5.000000,0.200000,36.810000,24.450000
max,51290.00000,99301.000000,22638.480000,14.000000,0.850000,8399.976000,933.570000

In [18]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [24]:
x=df.dropna(axis = 1)
x.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
5,22732,IN-2013-42360,28-06-2013,01-07-2013,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,...,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.35,Critical
6,30570,IN-2011-81826,07-11-2011,09-11-2011,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,...,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.77,Critical
7,31192,IN-2012-86369,14-04-2012,18-04-2012,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,...,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.4800,878.38,High
8,40155,CA-2014-135909,14-10-2014,21-10-2014,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,1906.4850,867.69,Low
9,40936,CA-2012-116638,28-01-2012,31-01-2012,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical

In [26]:
cust_id = df['Customer ID']

In [27]:
print(cust_id)

0        RH-19495
1        JR-16210
2        CR-12730
3        KM-16375
4         RH-9495
           ...
51285    KE-16420
51286    ZC-21910
51287    LB-16795
51288    RB-19795
51289    MC-18100
Name: Customer ID, Length: 51290, dtype: object

In [52]:
shipment_hist = df[['Order ID','Ship Mode','Customer ID','Customer Name','City','State','Product Name','Profit']]
shipment_hist

,Order ID,Ship Mode,Customer ID,Customer Name,City,State,Product Name,Profit
0,CA-2012-124891,Same Day,RH-19495,Rick Hansen,New York City,New York,Plantronics CS510 - Over-the-Head monaural Wir...,762.1845
1,IN-2013-77878,Second Class,JR-16210,Justin Ritter,Wollongong,New South Wales,"Novimex Executive Leather Armchair, Black",-288.7650
2,IN-2013-71249,First Class,CR-12730,Craig Reiter,Brisbane,Queensland,"Nokia Smart Phone, with Caller ID",919.9710
3,ES-2013-1579342,First Class,KM-16375,Katherine Murray,Berlin,Berlin,"Motorola Smart Phone, Cordless",-96.5400
4,SG-2013-4320,Same Day,RH-9495,Rick Hansen,Dakar,Dakar,"Sharp Wireless Fax, High-Speed",311.5200
...,...,...,...,...,...,...,...,...
51285,IN-2014-62366,Same Day,KE-16420,Katrina Edelman,Kure,Hiroshima,"Advantus Thumb Tacks, 12 Pack",4.5000
51286,US-2014-102288,Standard Class,ZC-21910,Zuschuss Carroll,Houston,Texas,Hoover Replacement Belt for Commercial Guardsm...,-1.1100
51287,US-2013-155768,Same Day,LB-16795,Laurel Beltran,Oxnard,California,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",11.2308
51288,MX-2012-140767,Standard Class,RB-19795,Ross Baird,Valinhos,São Paulo,"Acco Index Tab, Economy",2.4000
51289,MX-2012-134460,Second Class,MC-18100,Mick Crebagga,Tipitapa,Managua,"Eaton Computer Printout Paper, 8.5 x 11",1.8000

In [60]:
print(df[df['Category']=='Technology'])

       Row ID         Order ID  Order Date   Ship Date       Ship Mode  \
0       32298   CA-2012-124891  31-07-2012  31-07-2012        Same Day
2       25330    IN-2013-71249  17-10-2013  18-10-2013     First Class
3       13524  ES-2013-1579342  28-01-2013  30-01-2013     First Class
4       47221     SG-2013-4320  05-11-2013  06-11-2013        Same Day
5       22732    IN-2013-42360  28-06-2013  01-07-2013    Second Class
...       ...              ...         ...         ...             ...
51151   43296     PL-2011-5380  07-04-2011  09-04-2011    Second Class
51178   47992     SU-2014-3390  02-01-2014  06-01-2014  Standard Class
51219   35382   CA-2013-111913  05-08-2013  07-08-2013    Second Class
51237   31783   CA-2014-140963  11-06-2014  14-06-2014     First Class
51259   39396   CA-2013-169663  11-03-2013  14-03-2013     First Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
5        JM-15655       Jim Mitchum    Corporate         Sydney
...           ...               ...          ...            ...
51151     DB-2910       Daniel Byrd  Home Office         Poznan
51178     JM-5250      Janet Martin     Consumer      Bur Sudan
51219    LC-16930    Linda Cazamias    Corporate     Sacramento
51237    MT-18070     Michelle Tran  Home Office    Los Angeles
51259    RH-19510    Rick Huthwaite  Home Office    Los Angeles

                 State  ...        Product ID    Category Sub-Category  \
0             New York  ...   TEC-AC-10003033  Technology  Accessories
2           Queensland  ...   TEC-PH-10004664  Technology       Phones
3               Berlin  ...   TEC-PH-10004583  Technology       Phones
4                Dakar  ...  TEC-SHA-10000501  Technology      Copiers
5      New South Wales  ...   TEC-PH-10000030  Technology       Phones
...                ...  ...               ...         ...          ...
51151   Greater Poland  ...  TEC-EPS-10003473  Technology     Machines
51178          Red Sea  ...  TEC-MOT-10001088  Technology       Phones
51219       California  ...   TEC-PH-10002275  Technology       Phones
51237       California  ...   TEC-PH-10001924  Technology       Phones
51259       California  ...   TEC-AC-10003038  Technology  Accessories

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
5                    Samsung Smart Phone, with Caller ID  2862.675        5
...                                                  ...       ...      ...
51151                              Epson Phone, Wireless    80.970        1
51178                          Motorola Audio Dock, VoIP   173.460        1
51219                     Mitel 5320 IP Phone VoIP phone   302.384        2
51237           iHome FM Clock Radio with Lightning Dock   279.960        5
51259         Kingston Digital DataTraveler 16GB USB 2.0    26.850        3

      Discount    Profit  Shipping Cost  Order Priority
0          0.0  762.1845         933.57        Critical
2          0.1  919.9710         915.49          Medium
3          0.1  -96.5400         910.16          Medium
4          0.0  311.5200         903.04        Critical
5          0.1  763.2750         897.35        Critical
...        ...       ...            ...             ...
51151      0.0   36.4200           0.10          Medium
51178      0.0   50.2800           0.09          Medium
51219      0.2   30.2384           0.06          Medium
51237      0.2   17.4975           0.05            High
51259      0.0    5.1015           0.04          Medium

[10141 rows x 24 columns]

In [67]:
print(df[['Category','Ship Mode','Discount','Profit']])

              Category       Ship Mode  Discount    Profit
0           Technology        Same Day       0.0  762.1845
1            Furniture    Second Class       0.1 -288.7650
2           Technology     First Class       0.1  919.9710
3           Technology     First Class       0.1  -96.5400
4           Technology        Same Day       0.0  311.5200
...                ...             ...       ...       ...
51285  Office Supplies        Same Day       0.0    4.5000
51286  Office Supplies  Standard Class       0.8   -1.1100
51287  Office Supplies        Same Day       0.0   11.2308
51288  Office Supplies  Standard Class       0.0    2.4000
51289  Office Supplies    Second Class       0.0    1.8000

[51290 rows x 4 columns]

In [62]:
print(df[df['Order Date']=='04-07-2011'])

       Row ID         Order ID  Order Date   Ship Date       Ship Mode  \
2714    11911  IT-2011-2876489  04-07-2011  08-07-2011  Standard Class
9553    38029   CA-2011-120096  04-07-2011  07-07-2011     First Class
10821   27387    ID-2011-40953  04-07-2011  07-07-2011     First Class
14648   23183    IN-2011-47414  04-07-2011  10-07-2011  Standard Class
20781    8392   MX-2011-164574  04-07-2011  10-07-2011  Standard Class
27138   27385    ID-2011-40953  04-07-2011  07-07-2011     First Class
27302   38030   CA-2011-120096  04-07-2011  07-07-2011     First Class
27618   27386    ID-2011-40953  04-07-2011  07-07-2011     First Class
36331    3830   MX-2011-114615  04-07-2011  06-07-2011     First Class
42220   27384    ID-2011-40953  04-07-2011  07-07-2011     First Class
46126   38458   CA-2011-138709  04-07-2011  09-07-2011  Standard Class
47574   38459   CA-2011-138709  04-07-2011  09-07-2011  Standard Class
50844   43285     UP-2011-7960  04-07-2011  11-07-2011  Standard Class

      Customer ID      Customer Name    Segment              City  \
2714     CB-12415   Christy Brittain   Consumer            Drancy
9553     KE-16420    Katrina Edelman  Corporate            Aurora
10821    AA-10315         Alex Avila   Consumer          Marikina
14648    JS-16030          Joy Smith   Consumer  Ho Chi Minh City
20781    TB-21400   Tom Boeckenhauer   Consumer           Managua
27138    AA-10315         Alex Avila   Consumer          Marikina
27302    KE-16420    Katrina Edelman  Corporate            Aurora
27618    AA-10315         Alex Avila   Consumer          Marikina
36331    DL-13315  Delfina Latchford   Consumer         La Romana
42220    AA-10315         Alex Avila   Consumer          Marikina
46126    MS-17770   Maxwell Schwartz   Consumer          Richmond
47574    MS-17770   Maxwell Schwartz   Consumer          Richmond
50844    SV-10785   Stewart Visinsky   Consumer   Dnipropetrovs'k

                  State  ...        Product ID         Category Sub-Category  \
2714      Ile-de-France  ...   OFF-ST-10000922  Office Supplies      Storage
9553           Colorado  ...   OFF-PA-10001977  Office Supplies        Paper
10821  National Capital  ...   OFF-SU-10001308  Office Supplies     Supplies
14648  Ho Chí Minh City  ...   OFF-EN-10003413  Office Supplies    Envelopes
20781           Managua  ...   OFF-AR-10003245  Office Supplies          Art
27138  National Capital  ...   OFF-LA-10000425  Office Supplies       Labels
27302          Colorado  ...   OFF-AP-10000692  Office Supplies   Appliances
27618  National Capital  ...   TEC-AC-10004704       Technology  Accessories
36331         La Romana  ...   FUR-CH-10002882        Furniture       Chairs
42220  National Capital  ...   OFF-SU-10003723  Office Supplies     Supplies
46126          Virginia  ...   OFF-PA-10004734  Office Supplies        Paper
47574          Virginia  ...   OFF-BI-10000145  Office Supplies      Binders
50844   Dnipropetrovs'k  ...  OFF-NOV-10004968  Office Supplies       Labels

                                            Product Name     Sales Quantity  \
2714                               Eldon File Cart, Blue  799.8480        7
9553                                           Xerox 194  177.5360        4
10821                          Fiskars Trimmer, Serrated  278.8500       13
14648  Jiffy Interoffice Envelope, with clear poly wi...  248.9004        6
20781                        Binney & Smith Canvas, Blue  171.2000        5
27138                Avery Shipping Labels, Alphabetical   44.9295        7
27302          Fellowes Mighty 8 Compact Surge Protector   32.4320        2
27618                        SanDisk Numeric Keypad, USB   29.2380        1
36331           Harbour Creations Bag Chairs, Adjustable  102.5760        3
42220                           Elite Shears, High Speed   51.7110        2
46126                   Southworth Structures Collection   21.8400        3
47574                         Zipper Ring Binder Pockets   15.6000        5
50844               Novimex Removable Labels, Adjustable    7.7700        1

      Discount    Profit  Shipping Cost  Order Priority
2714      0.10  -71.2320         106.98            High
9553      0.20   62.1376          34.66        Critical
10821     0.45 -141.9600          30.01            High
14648     0.17   35.9604          20.36          Medium
20781     0.00   42.8000          11.68          Medium
27138     0.45   -4.2105           6.91            High
27302     0.20    3.2432           6.83        Critical
27618     0.45   -8.5320           6.66            High
36331     0.20   26.9160           3.20            High
42220     0.45  -23.5290           1.77            High
46126     0.00   10.9200           1.04          Medium
47574     0.00    7.6440           0.80          Medium
50844     0.00    0.0000           0.19          Medium

[13 rows x 24 columns]